<?php
namespace Brickoo\Module;


require_once 'C:\Users\Celli\dropbox\Brickoo\Description.php';

/**
 * Test class for Description.
 * Generated by PHPUnit on 2012-02-17 at 18:39:03.
 */
class DescriptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Description
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Description;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Brickoo\Module\Description::getVendor
     * @todo Implement testGetVendor().
     */
    public function testGetVendor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setVendor
     * @todo Implement testSetVendor().
     */
    public function testSetVendor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::getWebsite
     * @todo Implement testGetWebsite().
     */
    public function testGetWebsite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setWebsite
     * @todo Implement testSetWebsite().
     */
    public function testSetWebsite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::getContact
     * @todo Implement testGetContact().
     */
    public function testGetContact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setContact
     * @todo Implement testSetContact().
     */
    public function testSetContact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::getStatus
     * @todo Implement testGetStatus().
     */
    public function testGetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setStatus
     * @todo Implement testSetStatus().
     */
    public function testSetStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::getVersion
     * @todo Implement testGetVersion().
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setVersion
     * @todo Implement testSetVersion().
     */
    public function testSetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::getDescription
     * @todo Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Brickoo\Module\Description::setDescription
     * @todo Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
